package com.xpenzo.ml.models

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Unit tests for [SentencePieceTokenizer].
 *
 * These tests use a minimal synthetic proto that exercises the parser without
 * needing the actual xpenz_bpe.model asset.
 *
 * PARITY NOTE: When the real model is available, run [goldenParityTest] to verify
 * that the Kotlin tokenizer produces the same token IDs as the Python tokenizer
 * for the same input strings. Any mismatch will silently kill accuracy.
 */
class SentencePieceTokenizerTest {

    /** Build a minimal SentencePiece proto with a small hand-crafted vocabulary. */
    private fun buildMinimalModel(pieces: List<Pair<String, Float>>): ByteArray {
        val out = mutableListOf<Byte>()

        pieces.forEach { (piece, score) ->
            // Outer tag: field 1, wire type 2 (length-delimited)
            val subMsg = mutableListOf<Byte>()

            // piece field (tag=0x0A, then length-prefixed UTF-8 bytes)
            val pieceBytes = piece.toByteArray(Charsets.UTF_8)
            subMsg.add(0x0A.toByte())
            subMsg.addAll(encodeVarint(pieceBytes.size.toLong()))
            subMsg.addAll(pieceBytes.toList())

            // score field (tag=0x15, then 4-byte little-endian float)
            subMsg.add(0x15.toByte())
            val bits = java.lang.Float.floatToIntBits(score)
            subMsg.add((bits and 0xFF).toByte())
            subMsg.add(((bits shr 8) and 0xFF).toByte())
            subMsg.add(((bits shr 16) and 0xFF).toByte())
            subMsg.add(((bits shr 24) and 0xFF).toByte())

            // Outer length-delimited field
            out.add(0x0A.toByte())
            out.addAll(encodeVarint(subMsg.size.toLong()))
            out.addAll(subMsg)
        }
        return out.toByteArray()
    }

    private fun encodeVarint(v: Long): List<Byte> {
        val result = mutableListOf<Byte>()
        var rem = v
        do {
            var b = (rem and 0x7F).toByte()
            rem = rem ushr 7
            if (rem != 0L) b = (b.toInt() or 0x80).toByte()
            result.add(b)
        } while (rem != 0L)
        return result
    }

    private fun buildTestTokenizer(): SentencePieceTokenizer {
        val vocab = listOf(
            "<pad>" to 0f,   // id=0
            "<unk>" to 0f,   // id=1
            "<s>" to 0f,     // id=2 (BOS)
            "</s>" to 0f,    // id=3 (EOS)
            "▁swiggy" to -1f,
            "▁zomato" to -1.2f,
            "▁food" to -2f,
            "▁de" to -3f,
            "livery" to -3.1f,
            "▁#" to -4f,
            "#" to -4.1f,
            "▁unknown" to -5f,
        )
        return SentencePieceTokenizer(buildMinimalModel(vocab))
    }

    @Test
    fun `vocab size matches piece count`() {
        val tok = buildTestTokenizer()
        assertEquals(12, tok.vocabSize)
    }

    @Test
    fun `encode single known word produces BOS word EOS`() {
        val tok = buildTestTokenizer()
        val ids = tok.encode("swiggy", maxLen = 8)
        assertEquals(SentencePieceTokenizer.BOS_ID, ids[0])
        // "▁swiggy" is id=4
        assertEquals(4, ids[1])
        assertEquals(SentencePieceTokenizer.EOS_ID, ids[2])
        assertEquals(SentencePieceTokenizer.PAD_ID, ids[3])
    }

    @Test
    fun `encode empty string produces BOS EOS PAD`() {
        val tok = buildTestTokenizer()
        val ids = tok.encode("", maxLen = 8)
        assertEquals(SentencePieceTokenizer.BOS_ID, ids[0])
        assertEquals(SentencePieceTokenizer.EOS_ID, ids[1])
        assertEquals(SentencePieceTokenizer.PAD_ID, ids[2])
    }

    @Test
    fun `output length is always maxLen`() {
        val tok = buildTestTokenizer()
        assertEquals(32, tok.encode("swiggy zomato food delivery", maxLen = 32).size)
        assertEquals(8, tok.encode("swiggy", maxLen = 8).size)
    }

    @Test
    fun `unknown character maps to UNK_ID`() {
        val tok = buildTestTokenizer()
        val ids = tok.encode("xyz_unknown_merchant", maxLen = 16)
        // Some tokens will be <unk>
        assertTrue(ids.contains(SentencePieceTokenizer.UNK_ID))
    }

    @Test
    fun `normalized merchant digits replaced with hash tokenizes correctly`() {
        val tok = buildTestTokenizer()
        // "#" should map to "▁#" (id=9) or "#" (id=10).
        // Use "swiggy" (in the test vocab) so the word doesn't expand into per-char
        // <unk>s that would overflow maxLen before the '#' is reached.
        val ids = tok.encode("swiggy #", maxLen = 8)
        val knownIds = setOf(9, 10) // "▁#" or "#"
        assertTrue(ids.any { it in knownIds })
    }

    /**
     * GOLDEN PARITY TEST — run this against the real model.
     *
     * Expected IDs were generated by running:
     *   import sentencepiece as spm
     *   sp = spm.SentencePieceProcessor()
     *   sp.Load("xpenz_bpe.model")
     *   ids = sp.encode("<bos> swiggy food delivery <eos>", out_type=int)
     *
     * Update the expected values after generating them from the Python tokenizer.
     * This test is @Test-commented out until the golden IDs are filled in.
     */
    // @Test
    fun goldenParityTest_swiggyFoodDelivery() {
        // TODO: fill in after running Python tokenizer on the real model
        // val goldenIds = intArrayOf(2, ???, 3)
        // val tok = SentencePieceTokenizer(File("xpenz_bpe.model").readBytes())
        // val ids = tok.encode("swiggy food delivery", maxLen = 32)
        // assertArrayEquals(goldenIds, ids)
    }
}
